alexmojaki/futurecoder

- backend/main/chapters/c05_if_statements.py
- backend/main/chapters/c06_lists.py
- backend/main/workers/limits.py
- backend/main/workers/worker.py
- poetry.lock
- pyproject.toml
- setup.cfg
So it'll be available in user's environment
> poetry: Add flake8, isort

- backend/main/chapters/c03_variables.py
Change the expression from `name` to `your_name` in page `Using Variables` of c03_variables.py
Ref: #23 
- New feature (non-breaking change which adds functionality)
I only change one page of this chapter because I think it is enough to present the rule
> feature(naming_rule): present naming_rule of python in the excercise of c03_variables

- backend/main/workers/master.py
Trying to deal with the sort of problem mentioned in #28 or #47. If someone could try fiddling with the deployment to test that'd be great - @BobAnkh?
> Try to make system more robust to random failures by also recreating queues when restarting processes

- backend/main/chapters/c04_for_loops.py
- backend/main/models.py
- backend/main/text.py
- backend/main/views.py
- frontend/src/App.js
- frontend/src/book/store.js
Closes #43 
This changes a whole bunch of things so it needs testing badly. @spamegg1, @BobAnkh please play with the deployed environment and test it thoroughly if you can. Test running code, navigating between pages, moving steps in developer mode, hints, solutions, make sure that the editor/snoop/pythontutor are shown and hidden at the right times, open multiple tabs at different pages and make sure you can interact with them independently.
> Get page/step from frontend, not database, allowing multiple open pages at once

- README.md
I have updated Controls section in README with changes mentioned in #38 .
This closes #44 
Please review it to see if I missed something necessary.
> docs(README): update controls section

- .gitignore
- backend/main/chapters/c06_lists.py
- backend/main/chapters/c07_nested_loops.py
> Made bonus challenges concrete

- backend/main/chapters/c03_variables.py
- backend/main/chapters/c05_if_statements.py
- backend/main/chapters/c06_lists.py
- backend/main/chapters/c07_nested_loops.py
- backend/main/chapters/c09_boolean operators.py
- backend/main/text.py
- backend/main/utils/__init__.py
- frontend/src/App.js
- frontend/src/book/store.js
- frontend/src/css/main.scss
> Discourage copying most code, add convenient copy button for big snippets

- backend/main/chapters/c04_for_loops.py
- backend/main/chapters/c05_if_statements.py
- backend/main/chapters/c06_lists.py
- backend/main/chapters/c07_nested_loops.py
- backend/main/tests.py
- backend/main/text.py
- backend/main/utils/__init__.py
- backend/main/views.py
- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.js
- frontend/src/Hints.js
- frontend/src/book/store.js
- frontend/src/css/github-markdown.css
- frontend/src/css/main.scss
> Parsons problem in the solution

- backend/main/chapters/c06_lists.py
- backend/main/utils/__init__.py
I ran into some issues, you can see them in `TODO`s.
> improving lists chapter (fixes #34)

- backend/main/chapters/c06_lists.py
> Output predictions in List Functions pages #78

- backend/main/chapters/c08_nested_loops.py
- backend/main/chapters/c09_functions.py
- backend/main/tests/test_transcript.json
- backend/main/text.py
***Data migration warning!*** Deleted 2 steps from Chapter 8, first page "Introducing Nested Loops"
- also did a few `TODO message` steps
> Added f-strings to Chapters 8 and 9

- backend/main/chapters/c08_nested_loops.py
- backend/main/simple_settings.py
- backend/main/tests/test_transcript.json
- backend/main/workers/master.py
- backend/main/workers/worker.py
> Nested lists pages #100

- backend/main/chapters/c10_boolean operators.py
- should we add new hints? I don't think so.
> Rewrote chp10 `diagonal_winner` exercise to use nested lists

- backend/main/chapters/c10_boolean operators.py
- backend/main/chapters/c11_tic_tac_toe_project.py
- backend/main/tests/test_transcript.json
> added Page 1 of Chapter 11 Tic tac toe project (#3 #92)

- backend/main/chapters/c09_functions.py
- backend/main/tests/test_transcript.json
> added page on `return` to Chp9 Functions #93

- backend/main/chapters/c09_functions.py
- backend/main/exercises.py
- backend/main/tests/test_transcript.json
I went through chapters 9, 10, 11 interactively, everything looks in order. Predicted outputs look OK.
> changed `assert_equal` to use `repr` in error messages

- backend/main/chapters/c11_tic_tac_toe_project.py
- backend/main/tests/test_transcript.json
- backend/main/text.py
Happy New Year! #3
(the "next page" link right before bonus challenge is missing for now, because the next page doesn't exist yet)
> added page about newlines and `format_board` to Ch 11 Tic-Tac-Toe #3

- .github/workflows/pytest.yml
addressing #115
can be seen in action [here](https://github.com/alexmojaki/futurecoder/actions)
> added testing with Github Actions #115

- backend/main/templates/home.html
> Add video to home page

- backend/main/utils/__init__.py
- backend/main/workers/limits.py
- backend/setup.ps1
#123 
I haven't touched README.md yet, we can draft and discuss.
> windows compatibility tweaks #123

- frontend/src/shell/TerminalMessage.jsx
> keep traceback tooltip popup inside the window (fixes #107)

- backend/main/chapters/c11_tic_tac_toe_project.py
- backend/main/tests/test_transcript.json
Continuing #92
fixed the tests this time!
> added Types page to tic-tac-toe project (addressing #92)

- backend/main/views.py
This runs some dummy code when a user loads the course page. This starts up a user process if they don't have one already, so that users don't wait 10 seconds waiting for their code to run the first time.
> Start user process when user loads course

- .gitignore
- backend/main/static/css/main.scss
- backend/main/static/css/toc.scss
- backend/main/templates/base.html
- backend/main/templates/toc.html
> Re-style toc page

- core/workers/worker.py
- frontend/src/App.js
- frontend/src/book/store.js
- frontend/src/css/main.scss
- homepage/index.html
- tests/test_frontend.py
Happens at path #ide
Button in top right to switch between modes
Closes #118
> Full IDE mode: no course text, screen is filled with shell and editor.

- core/workers/worker.py
> Handle errors when finding and installing imports

- core/workers/birdseye.py
- core/workers/question_wizard.py
- core/workers/snoop.py
- core/workers/tracebacks.py
- core/workers/utils.py
- core/workers/worker.py
- frontend/src/App.js
- frontend/src/RunCode.js
- frontend/src/book/store.js
- frontend/src/load.py
- poetry.lock
- tests/test_steps.py
- tests/test_transcript.json
Adds a wizard to help with asking questions on StackOverflow etc.
This is still a WIP so for now there's no button. You can access it at `/course/#question`. Merging this because it includes other important fixes.
> Question wizard

- core/text.py
> Clarify expected code source in message

- .editorconfig
- frontend/src/App.js
- frontend/src/book/store.js
- frontend/src/components/HeaderLoginInfo.jsx
Hey Alex! Related to #207.
Popup should now close properly and I also added a page refresh on sign up. The flow seems better now, but you'll be the judge of that.
I've also moved login info into a new component as it's much more readable imo (wouldn't be a bad idea to move other components from App.js into their own respective files).
I've also added a .editorconfig file so that people who join don't need to configure their editors (tabs, spaces, new lines etc.). With intelliJ tools it works out of the box, but for vscode an extension is needed. I've left it for you to configure it for python files, and I've set js and css files based on what I've seen in the code.
> Fix dialog when signing up / logging in.

- core/chapters/c04_for_loops.py
- tests/test_transcript.json
> Remove spaces requirement from name_box exercise

- core/chapters/c04_for_loops.py
- core/chapters/c06_lists.py
- core/chapters/c08_nested_loops.py
- core/chapters/c11_tic_tac_toe_project.py
- core/markdown_extensions.py
- core/utils.py
- translations/english.po
- translations/generate_po_file.py
> Initial framework for generating po files for translation

- frontend/src/RunCode.js
> Run code in the editor with Ctrl+Enter

- frontend/src/RunCode.js
- frontend/src/book/store.js
> Wait until user and pages are loaded before running code

- core/chapters/c08_nested_loops.py
- tests/test_transcript.json
> change `upside_down_triangle_exercise` to use `+`

- frontend/src/RunCode.js
> Check SharedArrayBuffer again to show unsupported browser message

- homepage/index.html
> Resize video iframe to fit, fixing screen width and warpspeed performance

- homepage/static/css/brochure/layout/_hero.scss
Closes https://github.com/alexmojaki/futurecoder/issues/212
> Fix 3d terminal in safari

- homepage/index.html
- homepage/static/css/home.scss
> Add testimonials etc. to homepage

- frontend/src/Worker.js
Maybe this will help with #331
> Extract package to /tmp to ensure it's on sys.path

- frontend/public/index.html
> Remove viewport meta tag to avoid scaling on small devices

- frontend/package-lock.json
Same as https://github.com/alexmojaki/futurecoder/pull/337
> Bump async from 2.6.3 to 2.6.4

- frontend/src/App.js
- frontend/src/RunCode.js
- frontend/src/book/store.js
- frontend/src/store.js
Closes https://github.com/alexmojaki/futurecoder/issues/163
> Store user state with localForage for speed and offline usage

- frontend/src/App.js
- frontend/src/RunCode.js
- frontend/src/book/store.js
For https://github.com/alexmojaki/futurecoder/issues/326
> Record skipping steps in firebase database and analytics

- translations/locales/ta/index.html
@TamilNeram note that the original PR for this branch is closed, if you want to push more changes then you need to make another PR.
> Tamil homepage footer

- README.md
Just a minor thing in installation guide I noticed
> Update Python version to 3.11.2
